version: '3.4'

services:
  iig_pgsel_db:
    image: postgres

  iig_webapp_test:
    image: ${DOCKER_REGISTRY-}iigwebapptest
    build:
      context: .
      dockerfile: iig_webapp_test/Dockerfile

  clientapp:
    image: clientapp
    build:
      context: .
      dockerfile: /client-app/DockerfileEnv
    environment:
      NODE_ENV: production
    ports:
      - 80:80

volumes:
  postgres_data: